version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_documentos
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: main
      POSTGRES_DB: DocumentosDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
